# Generated by Django 5.2.7 on 2025-10-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        help_text="Formato: 000.000.000-00", max_length=14, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=255)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
